"""Поведение FarmLoop Stage 1: подготовка G-code без риска повторной обработки."""
from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from connector.printflow.farmloop import (
    BEGIN,
    END,
    FarmLoopError,
    prepare_file,
    prepare_gcode,
    profile_payload,
    validate_template,
)


SOURCE = """; generated by Bambu Studio
M104 S220
M140 S60
G28
G1 Z0.2 F1200
G1 X20 Y20 E1 F1800
M104 S0
M140 S0
"""

TEMPLATE = f"""{BEGIN}
; verified for the installed P1S Stage 1 kit
G1 X200 F6000
G1 Y250 F6000
{END}"""


class FarmLoopTemplateTests(unittest.TestCase):
    def test_valid_template_is_described(self):
        out = validate_template(TEMPLATE)
        self.assertEqual(out["profile"], "bambu-p1s-farmloop-stage1")
        self.assertEqual(out["commands"], 2)

    def test_empty_template_is_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "пустой"):
            validate_template(f"{BEGIN}\n; only comment\n{END}")

    def test_template_without_motion_is_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "движения"):
            validate_template(f"{BEGIN}\nM400\n{END}")

    def test_duplicate_markers_are_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "ровно один"):
            validate_template(TEMPLATE + "\n" + BEGIN + "\n" + END)


class FarmLoopPreparationTests(unittest.TestCase):
    def test_prepare_preserves_source_and_adds_metadata(self):
        output, report = prepare_gcode(
            SOURCE, TEMPLATE,
            metadata={"job_id": "job-7", "cycle": "2", "cycles": "10", "ams": "AMS1/3"},
        )
        self.assertTrue(output.startswith(SOURCE))
        self.assertIn(BEGIN, output)
        self.assertIn("; job_id: job-7", output)
        self.assertIn("; cycle: 2", output)
        self.assertIn("; ams: AMS1/3", output)
        self.assertTrue(report["injected"])
        self.assertEqual(output.count(BEGIN), 1)
        self.assertEqual(output.count(END), 1)

    def test_already_prepared_file_is_rejected(self):
        prepared, _ = prepare_gcode(SOURCE, TEMPLATE)
        with self.assertRaisesRegex(FarmLoopError, "уже содержит"):
            prepare_gcode(prepared, TEMPLATE)

    def test_non_fdm_source_is_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "сопла"):
            prepare_gcode("; just text\nG1 X1", TEMPLATE)

    def test_height_warning_does_not_silently_change_file(self):
        source = SOURCE + "\nG1 Z220 F600\n"
        output, report = prepare_gcode(source, TEMPLATE)
        self.assertIn("Высота", report["warnings"][0])
        self.assertIn("G1 Z220", output)

    def test_source_and_destination_must_differ(self):
        with tempfile.TemporaryDirectory() as folder:
            path = Path(folder) / "job.gcode"
            path.write_text(SOURCE, encoding="utf-8")
            with self.assertRaisesRegex(FarmLoopError, "разными"):
                prepare_file(path, path, TEMPLATE)

    def test_profile_is_explicit(self):
        payload = profile_payload()
        self.assertEqual(payload["printer"], "Bambu Lab P1S")
        self.assertEqual(payload["stage"], "Stage 1")
        self.assertTrue(payload["requires_verified_template"])


if __name__ == "__main__":
    unittest.main()
