"""Тесты разбора реальных форматов 3MF/G-code Bambu Studio / OrcaSlicer.

Покрывают баги, из-за которых «Обновить граммы» не находил вес:
  * ``estimated printing time (normal mode) = ...`` не парсилось (скобки);
  * ``slice_info.config`` в JSON с ключом ``plate`` вместо ``plates``
    молча давал 0 г / 0 мин;
  * одиночная плита как dict, формат ``plate_1``, ``used_m`` без ``used_g``.
"""
from __future__ import annotations

import json
import pathlib
import sys
import tempfile
import unittest
import zipfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "connector"))

from connector.printflow.estimate import (  # noqa: E402
    _parse_gcode_head,
    estimate_file,
    normalize_slice_info,
)


def _write_3mf(tmp: pathlib.Path, files: dict[str, str]) -> pathlib.Path:
    path = tmp / "model.3mf"
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("[Content_Types].xml", "<xml/>")
        for name, content in files.items():
            zf.writestr(name, content)
    return path


class GcodeHeaderTests(unittest.TestCase):
    def test_bambu_estimated_time_with_mode_in_parens(self):
        head = _parse_gcode_head(
            "; estimated printing time (normal mode) = 284m 19s\n"
            "; total filament used [g] = 92.18\n"
            "; filament_type = PLA\n"
            "; filament_colour = #FFFFFF\n"
            "G1 X0\n"
        )
        self.assertAlmostEqual(head["minutes"], 284.3, places=1)
        self.assertAlmostEqual(head["grams"], 92.2, places=1)
        self.assertEqual(head["material"], "PLA")

    def test_bambu_time_no_space_before_paren(self):
        head = _parse_gcode_head(
            "; estimated printing time(normal mode) = 1h 20m\n"
            "; total filament used [g] = 50\n"
        )
        self.assertAlmostEqual(head["minutes"], 80.0, places=1)

    def test_silent_and_sport_modes(self):
        for label in ("silent mode", "sport mode", "normal mode"):
            head = _parse_gcode_head(
                f"; estimated printing time ({label}) = 45m\n"
                "; total filament used [g] = 10\n"
            )
            self.assertAlmostEqual(head["minutes"], 45.0, places=1, msg=label)

    def test_orca_slicer_header(self):
        head = _parse_gcode_head(
            "; generated by OrcaSlicer 2.2.0\n"
            "; estimated printing time (normal mode) = 1h 20m\n"
            "; total filament used [g] = 12.34\n"
            "; filament_type = PLA\n"
            "; filament_colour = #FF0000\n"
        )
        self.assertAlmostEqual(head["minutes"], 80.0, places=1)
        self.assertAlmostEqual(head["grams"], 12.3, places=1)
        self.assertEqual(head["material"], "PLA")

    def test_total_filament_weight_variant(self):
        head = _parse_gcode_head(
            "; total filament weight [g] = 92.18\n"
            "; filament used [g] = 0.00, 0.00, 92.18\n"
        )
        self.assertAlmostEqual(head["grams"], 92.2, places=1)

    def test_multicolor_comma_values_sum(self):
        head = _parse_gcode_head(
            "; filament used [g] = 12.34, 3.20\n"
            "; TIME:600\n"
        )
        # total отсутствует, поэтому per-filament суммируется
        self.assertAlmostEqual(head["grams"], 15.5, places=1)

    def test_print_time_synonyms(self):
        for line in (
            "; print time = 1h 20m\n",
            "; print_time = 1h 20m\n",
            "; total estimated time = 1h 20m\n",
            "; model printing time = 1h 20m\n",
        ):
            head = _parse_gcode_head(line + "; filament used [g] = 5\n")
            self.assertAlmostEqual(head["minutes"], 80.0, places=1, msg=line)


class SliceInfoNormalizeTests(unittest.TestCase):
    def test_json_plural_plates(self):
        si = normalize_slice_info({
            "plates": [{"index": 1, "prediction": 4823, "weight": 23.45,
                        "filaments": [{"used_g": 23.45, "type": "PLA"}]}],
        })
        self.assertEqual(len(si["plates"]), 1)
        self.assertAlmostEqual(si["plates"][0]["grams"], 23.4, places=1)
        self.assertAlmostEqual(si["plates"][0]["minutes"], 80.4, places=1)

    def test_json_singular_plate_list(self):
        """Раньше JSON с ключом 'plate' возвращал 0 г/мин — баг №1."""
        si = normalize_slice_info({
            "plate": [{"index": 1, "prediction": 4823, "weight": 23.45,
                       "filament": [{"used_g": 23.45, "type": "PLA"}]}],
        })
        self.assertEqual(len(si["plates"]), 1)
        self.assertAlmostEqual(si["plates"][0]["grams"], 23.4, places=1)

    def test_json_singular_plate_dict(self):
        si = normalize_slice_info({
            "plate": {"index": 1, "prediction": 4823, "weight": 23.45,
                      "filament": [{"used_g": 23.45, "type": "PLA"}]},
        })
        self.assertEqual(len(si["plates"]), 1)
        self.assertAlmostEqual(si["plates"][0]["grams"], 23.4, places=1)

    def test_old_plate_n_keys_format(self):
        si = normalize_slice_info({
            "plate_count": 1,
            "plate_1": {"index": 1, "prediction": 4823, "weight": 23.45,
                        "filaments": [{"used_g": 23.45, "type": "PLA"}]},
        })
        self.assertEqual(len(si["plates"]), 1)
        self.assertAlmostEqual(si["plates"][0]["grams"], 23.4, places=1)

    def test_used_m_only_converted_to_grams(self):
        """Bambu иногда отдаёт used_g=0 при заполненном used_m."""
        si = normalize_slice_info({
            "plate": [{"index": 1, "prediction": 4823, "weight": 0,
                       "filament": [{"used_g": 0, "used_m": 8.42, "type": "PLA"}]}],
        })
        plate = si["plates"][0]
        self.assertGreater(plate["grams"], 0)
        self.assertGreater(plate["filaments"][0]["used_g"], 0)

    def test_xml_format_still_works(self):
        from connector.printflow.estimate import _parse_slice_info_xml
        xml = (
            '<?xml version="1.0"?><config><plate>'
            '<metadata key="index" value="1"/>'
            '<metadata key="prediction" value="4823"/>'
            '<metadata key="weight" value="23.45"/>'
            '<filament id="1" type="PLA" color="#FF0000" used_g="23.45"/>'
            '</plate></config>'
        )
        parsed = _parse_slice_info_xml(xml)
        si = normalize_slice_info(parsed)
        self.assertEqual(len(si["plates"]), 1)
        self.assertAlmostEqual(si["plates"][0]["grams"], 23.4, places=1)
        self.assertAlmostEqual(si["plates"][0]["minutes"], 80.4, places=1)


class ThreeMFEstimateTests(unittest.TestCase):
    def test_json_singular_plate_returns_grams(self):
        """Главный баг: выбор файла со slice_info в JSON не давал граммов."""
        with tempfile.TemporaryDirectory() as td:
            tmp = pathlib.Path(td)
            si = {
                "plate": [{
                    "index": 1, "prediction": 4823, "weight": 23.45,
                    "filament": [{"used_g": 23.45, "type": "PLA", "color": "#FF0000"}],
                }],
            }
            path = _write_3mf(tmp, {
                "Metadata/slice_info.config": json.dumps(si),
                "Metadata/plate_1.gcode": ";BambuStudio\nG1\n",
            })
            est = estimate_file(path)
            self.assertAlmostEqual(est["grams"], 23.4, places=1)
            self.assertAlmostEqual(est["minutes"], 80.4, places=1)
            self.assertEqual(est["material"], "PLA")
            self.assertAlmostEqual(est["total_grams"], 23.4, places=1)

    def test_xml_slice_info_only_no_gcode_headers(self):
        with tempfile.TemporaryDirectory() as td:
            tmp = pathlib.Path(td)
            xml = (
                '<?xml version="1.0"?><config><plate>'
                '<metadata key="index" value="1"/>'
                '<metadata key="prediction" value="4823"/>'
                '<metadata key="weight" value="23.45"/>'
                '<filament id="1" type="PLA" color="#FF0000" used_g="23.45"/>'
                '</plate></config>'
            )
            path = _write_3mf(tmp, {
                "Metadata/slice_info.config": xml,
                "Metadata/plate_1.gcode": "; no grams here\nG1\n",
            })
            est = estimate_file(path)
            self.assertAlmostEqual(est["grams"], 23.4, places=1)

    def test_multiplate_sums_total_grams(self):
        with tempfile.TemporaryDirectory() as td:
            tmp = pathlib.Path(td)
            si = {
                "plates": [
                    {"index": 1, "prediction": 17059, "weight": 213.0,
                     "filaments": [{"used_g": 213.0, "type": "PLA"}]},
                    {"index": 2, "prediction": 5000, "weight": 50.0,
                     "filaments": [{"used_g": 50.0, "type": "PLA"}]},
                ],
            }
            path = _write_3mf(tmp, {
                "Metadata/slice_info.config": json.dumps(si),
                "Metadata/plate_1.gcode": "G1\n",
                "Metadata/plate_2.gcode": "G1\n",
            })
            est = estimate_file(path)
            self.assertAlmostEqual(est["total_grams"], 263.0, places=1)
            self.assertEqual(est["plate_count"], 2)

    def test_gcode_time_mode_in_parens_in_3mf(self):
        with tempfile.TemporaryDirectory() as td:
            tmp = pathlib.Path(td)
            gcode = (
                "; estimated printing time (normal mode) = 284m 19s\n"
                "; total filament used [g] = 92.18\n"
                "; filament_type = PLA\n"
            )
            path = _write_3mf(tmp, {"Metadata/plate_1.gcode": gcode})
            est = estimate_file(path)
            self.assertAlmostEqual(est["minutes"], 284.3, places=1)
            self.assertAlmostEqual(est["grams"], 92.2, places=1)

    def test_used_m_fallback_in_3mf(self):
        with tempfile.TemporaryDirectory() as td:
            tmp = pathlib.Path(td)
            si = {
                "plate": [{
                    "index": 1, "prediction": 4823, "weight": 0,
                    "filament": [{"used_g": 0, "used_m": 8.42, "type": "PLA"}],
                }],
            }
            path = _write_3mf(tmp, {
                "Metadata/slice_info.config": json.dumps(si),
                "Metadata/plate_1.gcode": "G1\n",
            })
            est = estimate_file(path)
            self.assertGreater(est["grams"], 0)


if __name__ == "__main__":
    unittest.main()
