"""Поведение FarmLoop Stage 1: подготовка G-code без риска повторной обработки."""
from __future__ import annotations

import tempfile
import types
import unittest
from pathlib import Path

from connector.printflow.farmloop import (
    BEGIN,
    END,
    FarmLoopError,
    prepare_file,
    prepare_gcode,
    profile_payload,
    validate_template,
)


SOURCE = """; generated by Bambu Studio
M104 S220
M140 S60
G28
G1 Z0.2 F1200
G1 X20 Y20 E1 F1800
M104 S0
M140 S0
"""

TEMPLATE = f"""{BEGIN}
; verified for the installed P1S Stage 1 kit
G1 X200 F6000
G1 Y250 F6000
{END}"""


class FarmLoopRouteTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        import connector.printflow.routes_farmloop  # noqa: F401

    def test_profile_reports_uninstalled_template_without_claiming_ready(self):
        from connector.printflow.router import router
        code, payload = router.dispatch(None, "GET", "/api/farmloop/profile", query={})
        self.assertEqual(code, 200)
        self.assertEqual(payload["id"], "bambu-p1s-farmloop-stage1")
        self.assertFalse(payload["template_installed"])
        self.assertFalse(payload["can_prepare"])
        self.assertIn("шаблон", payload["blocked_reason"])


class FarmLoopTemplateTests(unittest.TestCase):
    def test_valid_template_is_described(self):
        out = validate_template(TEMPLATE)
        self.assertEqual(out["profile"], "bambu-p1s-farmloop-stage1")
        self.assertEqual(out["commands"], 2)

    def test_empty_template_is_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "пустой"):
            validate_template(f"{BEGIN}\n; only comment\n{END}")

    def test_template_without_motion_is_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "движения"):
            validate_template(f"{BEGIN}\nM400\n{END}")

    def test_duplicate_markers_are_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "ровно один"):
            validate_template(TEMPLATE + "\n" + BEGIN + "\n" + END)


class FarmLoopPreparationTests(unittest.TestCase):
    def test_prepare_preserves_source_and_adds_metadata(self):
        output, report = prepare_gcode(
            SOURCE, TEMPLATE,
            metadata={"job_id": "job-7", "cycle": "2", "cycles": "10", "ams": "AMS1/3"},
        )
        self.assertTrue(output.startswith(SOURCE))
        self.assertIn(BEGIN, output)
        self.assertIn("; job_id: job-7", output)
        self.assertIn("; cycle: 2", output)
        self.assertIn("; ams: AMS1/3", output)
        self.assertTrue(report["injected"])
        self.assertEqual(output.count(BEGIN), 1)
        self.assertEqual(output.count(END), 1)

    def test_already_prepared_file_is_rejected(self):
        prepared, _ = prepare_gcode(SOURCE, TEMPLATE)
        with self.assertRaisesRegex(FarmLoopError, "уже содержит"):
            prepare_gcode(prepared, TEMPLATE)

    def test_non_fdm_source_is_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "сопла"):
            prepare_gcode("; just text\nG1 X1", TEMPLATE)

    def test_height_warning_does_not_silently_change_file(self):
        source = SOURCE + "\nG1 Z220 F600\n"
        output, report = prepare_gcode(source, TEMPLATE)
        self.assertIn("Высота", report["warnings"][0])
        self.assertIn("G1 Z220", output)

    def test_source_and_destination_must_differ(self):
        with tempfile.TemporaryDirectory() as folder:
            path = Path(folder) / "job.gcode"
            path.write_text(SOURCE, encoding="utf-8")
            with self.assertRaisesRegex(FarmLoopError, "разными"):
                prepare_file(path, path, TEMPLATE)

    def test_profile_is_explicit(self):
        payload = profile_payload()
        self.assertEqual(payload["printer"], "Bambu Lab P1S")
        self.assertEqual(payload["stage"], "Stage 1")
        self.assertTrue(payload["requires_verified_template"])


class FarmLoopConstructorAndCleanTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        import connector.printflow.routes_farmloop  # noqa: F401

    def test_build_and_parse_template_blocks(self):
        from connector.printflow.farmloop import build_template_from_blocks, parse_template_blocks
        gcode = build_template_from_blocks(
            cooldown_temp=38, fan_assist=True, z_lift=18.0, pusher_y=242.0,
            pusher_speed=2500, custom_gcode="M300 S440 P100\n",
        )
        self.assertIn("M190 R38", gcode)
        self.assertIn("G1 Z18.0 F1200", gcode)
        self.assertIn("G1 Y242.0 F2500", gcode)
        self.assertIn("M300 S440 P100", gcode)
        blocks = parse_template_blocks(gcode)
        self.assertEqual(blocks["cooldown_temp"], 38)
        self.assertTrue(blocks["fan_assist"])
        self.assertEqual(blocks["z_lift"], 18.0)
        self.assertEqual(blocks["pusher_y"], 242.0)
        self.assertEqual(blocks["pusher_speed"], 2500)
        self.assertIn("M300", blocks["custom_gcode"])

    def test_template_get_and_post_lifecycle(self):
        import types
        from unittest import mock
        from connector.printflow.router import router
        with tempfile.TemporaryDirectory() as tmp:
            tmp_data = Path(tmp)
            with mock.patch("connector.printflow.routes_farmloop.DATA_DIR", tmp_data):
                # 1. Сначала шаблон не установлен
                code, res = router.dispatch(None, "GET", "/api/farmloop/template", query={})
                self.assertEqual(code, 200)
                self.assertFalse(res["template_installed"])
                self.assertTrue(res["gcode"])
                self.assertEqual(res["blocks"]["cooldown_temp"], 35)

                # 2. Сохраняем шаблон блоками конструктора
                api = types.SimpleNamespace(db=None)
                code, res = router.dispatch(api, "POST", "/api/farmloop/template", body={
                    "blocks": {
                        "cooldown_temp": 40,
                        "fan_assist": True,
                        "z_lift": 20.0,
                        "pusher_y": 240.0,
                        "pusher_speed": 2200,
                        "custom_gcode": "; comment\n",
                    }
                })
                self.assertEqual(code, 200)
                self.assertTrue(res["template_installed"])
                self.assertEqual(res["blocks"]["cooldown_temp"], 40)

                # 3. Теперь GET сообщает, что шаблон установлен
                code, res = router.dispatch(None, "GET", "/api/farmloop/template", query={})
                self.assertEqual(code, 200)
                self.assertTrue(res["template_installed"])
                self.assertEqual(res["blocks"]["cooldown_temp"], 40)

    def test_test_clean_safety_checks(self):
        import types
        from unittest import mock
        from connector.printflow.router import router
        with tempfile.TemporaryDirectory() as tmp:
            tmp_data = Path(tmp)
            with mock.patch("connector.printflow.routes_farmloop.DATA_DIR", tmp_data):
                sent_commands = []
                printer = types.SimpleNamespace(
                    id="p1",
                    record={"name": "Тестовый P1S"},
                    connected=True,
                    snapshot=lambda: {"printer": {"state": "IDLE", "bed_temp": 32}},
                    gcode=lambda cmd: sent_commands.append(cmd),
                )
                manager = types.SimpleNamespace(get=lambda pid: printer)
                api = types.SimpleNamespace(db=None, manager=manager)

                # 1. Отказ без подтверждения confirmed: true
                code, res = router.dispatch(api, "POST", "/api/farmloop/test-clean", body={})
                self.assertEqual(code, 400)
                self.assertIn("Подтвердите", res["error"])

                # 2. Отказ, если шаблон ещё не установлен
                code, res = router.dispatch(api, "POST", "/api/farmloop/test-clean", body={"confirmed": True})
                self.assertEqual(code, 400)
                self.assertIn("не установлен", res["error"])

                # Устанавливаем шаблон
                tmpl_dir = tmp_data / "farmloop-templates"
                tmpl_dir.mkdir(parents=True)
                (tmpl_dir / "bambu-p1s-farmloop-stage1.gcode").write_text(
                    f"{BEGIN}\nG1 Z10 F1200\nG1 Y200 F2400\n{END}\n", encoding="utf-8")

                # 3. Отказ, если принтер занят (RUNNING). 18.12.1: менеджер без
                # пула printers — станок берётся как «первый», а причина отказа
                # называется в перечне свободных («занят (статус: …)»).
                printer.snapshot = lambda: {"printer": {"state": "RUNNING", "bed_temp": 60}}
                code, res = router.dispatch(api, "POST", "/api/farmloop/test-clean", body={"confirmed": True})
                self.assertEqual(code, 400)
                self.assertIn("занят (статус: RUNNING)", res["error"])
                self.assertIn("«Тестовый P1S»", res["error"])
                self.assertIn("Нет свободного станка", res["error"])
                self.assertEqual([], sent_commands, "команды ушли на занятый станок")

                # 4. Успешный запуск, когда принтер IDLE
                printer.snapshot = lambda: {"printer": {"state": "IDLE", "bed_temp": 30}}
                code, res = router.dispatch(api, "POST", "/api/farmloop/test-clean", body={"confirmed": True})
                self.assertEqual(code, 200)
                self.assertTrue(res["ok"])
                self.assertEqual(res["executed_commands"], 2)
                self.assertEqual(sent_commands, ["G1 Z10 F1200", "G1 Y200 F2400"])


class FarmLoopTestCleanPrinterChoiceTests(unittest.TestCase):
    """18.12.1: «Тестовая очистка стола» выбирает станок, а не «первый в словаре».

    Панель слала ``{confirmed: true}`` без ``printer_id``, ``manager.get('')``
    возвращал ПЕРВЫЙ принтер словаря — занятый или отключённый, и кнопка
    отвечала «Принтер занят» при живом свободном станке рядом.
    """

    @classmethod
    def setUpClass(cls):
        import connector.printflow.routes_farmloop  # noqa: F401

    @staticmethod
    def _printer(pid: str, name: str, state: str = "IDLE", connected: bool = True):
        """Станок как его видит маршрут: record, connected, snapshot, gcode."""
        return types.SimpleNamespace(
            id=pid,
            record={"name": name},
            connected=connected,
            snapshot=lambda: {"printer": {"state": state}},
            gcode=lambda cmd: None,
        )

    @staticmethod
    def _manager(*printers):
        """Менеджер с пулом: имя атрибута именно ``printers`` (dict)."""
        pool = {printer.id: printer for printer in printers}
        return types.SimpleNamespace(
            printers=pool,
            get=lambda pid="": pool.get(pid) if pid else next(iter(pool.values()), None),
        )

    def _installed(self, tmp_data: Path) -> None:
        """Проверенный шаблон: без него маршрут не доходит до выбора станка."""
        folder = tmp_data / "farmloop-templates"
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "bambu-p1s-farmloop-stage1.gcode").write_text(
            f"{BEGIN}\nG1 Z10 F1200\nG1 Y200 F2400\n{END}\n", encoding="utf-8")

    def _dispatch(self, api, body: dict):
        from connector.printflow.router import router
        return router.dispatch(api, "POST", "/api/farmloop/test-clean", body=body)

    def test_auto_pick_takes_the_free_printer_not_the_first(self):
        from unittest import mock
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("connector.printflow.routes_farmloop.DATA_DIR", Path(tmp)):
                self._installed(Path(tmp))
                sent: list[str] = []
                busy = self._printer("p1", "P1S-1", state="RUNNING")
                offline = self._printer("p2", "P1S-2", connected=False)
                free = self._printer("p3", "P1S-3", state="IDLE")
                free.gcode = lambda cmd: sent.append(cmd)
                api = types.SimpleNamespace(db=None,
                                            manager=self._manager(busy, offline, free))
                code, res = self._dispatch(api, {"confirmed": True})
                self.assertEqual(200, code)
                self.assertEqual("p3", res["printer_id"], "выбран первый в словаре, а не свободный")
                self.assertEqual("P1S-3", res["printer"])
                self.assertTrue(res["auto_selected"])
                self.assertEqual(["G1 Z10 F1200", "G1 Y200 F2400"], sent)

    def test_finish_state_counts_as_free(self):
        from unittest import mock
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("connector.printflow.routes_farmloop.DATA_DIR", Path(tmp)):
                self._installed(Path(tmp))
                done = self._printer("p1", "P1S-1", state="FINISH")
                api = types.SimpleNamespace(db=None, manager=self._manager(done))
                code, res = self._dispatch(api, {"confirmed": True})
                self.assertEqual(200, code)
                self.assertEqual("p1", res["printer_id"])

    def test_all_busy_gives_400_with_the_list_of_reasons(self):
        from unittest import mock
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("connector.printflow.routes_farmloop.DATA_DIR", Path(tmp)):
                self._installed(Path(tmp))
                api = types.SimpleNamespace(db=None, manager=self._manager(
                    self._printer("p1", "P1S-1", state="RUNNING"),
                    self._printer("p2", "P1S-2", connected=False),
                ))
                code, res = self._dispatch(api, {"confirmed": True})
                self.assertEqual(400, code)
                self.assertIn("Нет свободного станка", res["error"])
                self.assertIn("«P1S-1» — занят (статус: RUNNING)", res["error"])
                self.assertIn("«P1S-2» — не подключен", res["error"])
                self.assertIn("Освободите станок или выберите другой в списке.", res["error"])
                self.assertEqual(2, len(res["blocked"]))

    def test_explicit_busy_printer_is_refused_with_its_own_reason(self):
        from unittest import mock
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("connector.printflow.routes_farmloop.DATA_DIR", Path(tmp)):
                self._installed(Path(tmp))
                sent: list[str] = []
                busy = self._printer("p1", "P1S-1", state="RUNNING")
                busy.gcode = lambda cmd: sent.append(cmd)
                free = self._printer("p2", "P1S-2", state="IDLE")
                api = types.SimpleNamespace(db=None, manager=self._manager(busy, free))
                code, res = self._dispatch(api, {"confirmed": True, "printer_id": "p1"})
                self.assertEqual(400, code)
                self.assertIn("«P1S-1»", res["error"])
                self.assertIn("занят (статус: RUNNING)", res["error"])
                self.assertEqual([], sent, "команды ушли на занятый станок")
                # Явный выбор свободного станка работает.
                code, res = self._dispatch(api, {"confirmed": True, "printer_id": "p2"})
                self.assertEqual(200, code)
                self.assertEqual("p2", res["printer_id"])
                self.assertFalse(res["auto_selected"])

    def test_unknown_printer_id_is_still_not_found(self):
        from unittest import mock
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("connector.printflow.routes_farmloop.DATA_DIR", Path(tmp)):
                self._installed(Path(tmp))
                api = types.SimpleNamespace(db=None, manager=self._manager(
                    self._printer("p1", "P1S-1")))
                code, res = self._dispatch(api, {"confirmed": True, "printer_id": "нет-такого"})
                self.assertEqual(400, code)
                self.assertIn("не найден", res["error"].lower())

    def test_empty_pool_says_to_add_a_printer(self):
        from unittest import mock
        with tempfile.TemporaryDirectory() as tmp:
            with mock.patch("connector.printflow.routes_farmloop.DATA_DIR", Path(tmp)):
                self._installed(Path(tmp))
                api = types.SimpleNamespace(db=None, manager=self._manager())
                code, res = self._dispatch(api, {"confirmed": True})
                self.assertEqual(400, code)
                self.assertIn("Принтеров нет", res["error"])

    def test_helper_blockers_and_names(self):
        from connector.printflow.routes_farmloop import (
            _pick_free_printer, _printer_name, _test_clean_blockers)
        busy = self._printer("p1", "P1S-1", state="PAUSE")
        offline = self._printer("p2", "P1S-2", state="IDLE", connected=False)
        free = self._printer("p3", "P1S-3", state="FINISH")
        self.assertEqual([], _test_clean_blockers(free))
        self.assertEqual(["занят (статус: PAUSE)"], _test_clean_blockers(busy))
        self.assertEqual(["не подключен"], _test_clean_blockers(offline))
        both = self._printer("p4", "P1S-4", state="UNKNOWN", connected=False)
        self.assertEqual(["не подключен", "занят (статус: UNKNOWN)"],
                         _test_clean_blockers(both))
        self.assertEqual("P1S-3", _printer_name(free))
        self.assertEqual("p1", _printer_name(types.SimpleNamespace(id="p1")),
                         "нет record — имя берётся из id, а не падает")
        picked, notes = _pick_free_printer(self._manager(busy, offline, free))
        self.assertIs(free, picked)
        self.assertEqual(["«P1S-1» — занят (статус: PAUSE)",
                          "«P1S-2» — не подключен"], notes)
        self.assertEqual((None, []), _pick_free_printer(types.SimpleNamespace()))


if __name__ == "__main__":
    unittest.main()
