"""Watch Folder: файл, который не попал в очередь, должен быть виден (17.0.18).

`manager.enqueue` бросает ValueError на файлах, которые печатать нельзя (логи,
таймлапс, ipcam). Раньше `_handle_file` глотал это в `except Exception: pass`,
а событие с `action=queue` уже ушло в ленту — оператор видел «файл принят»,
хотя печать не началась. Здесь проверяем, что причина возвращается и
регистрируется.
"""
from __future__ import annotations

import json
import pathlib
import sys
import tempfile
import unittest
from unittest import mock

ROOT = pathlib.Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(ROOT / "connector"))

from connector.printflow import watch_folder as watch_folder_mod  # noqa: E402
from connector.printflow.api import Api  # noqa: E402
from connector.printflow.db import Database  # noqa: E402
from connector.printflow.manager import PrinterManager  # noqa: E402
from connector.printflow.repo import Repo  # noqa: E402
from connector.printflow.watch_folder import WatchFolder, pick_warehouse_spool  # noqa: E402
from connector.tests.test_phase11 import make_db  # noqa: E402

SOURCE = pathlib.Path(__file__).resolve().parents[2] / "connector" / "printflow" / "watch_folder.py"


class FakeManager:
    """Замена менеджера печати: запоминает payload и умеет отказать."""

    def __init__(self, error: str = "", result=None):
        self.error = error
        self.result = result if result is not None else {"id": "job_1"}
        self.calls: list[dict] = []

    def enqueue(self, payload: dict):
        self.calls.append(payload)
        if self.error:
            raise ValueError(self.error)
        return self.result


class WatchFolderEnqueueTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.db = Database(pathlib.Path(self.tmp.name) / "watch.sqlite3")
        self.addCleanup(self.db.close)

    def watch(self, manager) -> WatchFolder:
        return WatchFolder(self.db, manager=manager, bus=None)

    def test_success_returns_true_and_sends_payload(self):
        manager = FakeManager()
        ok, reason = self.watch(manager)._enqueue("деталь.3mf", {}, "ord_1")
        self.assertTrue(ok)
        self.assertEqual("", reason)
        self.assertEqual(1, len(manager.calls))
        payload = manager.calls[0]
        self.assertEqual("деталь.3mf", payload["file"])
        self.assertEqual("деталь", payload["name"])
        self.assertEqual("ord_1", payload["order_id"])

    def test_manager_refusal_is_reported_not_swallowed(self):
        manager = FakeManager(error="Нельзя печатать логи, таймлапс и ipcam")
        ok, reason = self.watch(manager)._enqueue("ipcam.mp4.3mf", {}, "")
        self.assertFalse(ok)
        self.assertIn("Нельзя печатать", reason)

    def test_missing_manager_is_reported(self):
        ok, reason = self.watch(None)._enqueue("деталь.3mf", {}, "")
        self.assertFalse(ok)
        self.assertIn("менеджер", reason)

    def test_rejected_result_dict_is_reported(self):
        manager = FakeManager(result={"error": "принтер занят"})
        ok, reason = self.watch(manager)._enqueue("деталь.3mf", {}, "")
        self.assertFalse(ok)
        self.assertEqual("принтер занят", reason)


class WatchFolderCallerTests(unittest.TestCase):
    """Строковый контракт на вызывающий код: причину должна увидеть лента."""

    @classmethod
    def setUpClass(cls):
        cls.src = SOURCE.read_text(encoding="utf-8")

    def test_queue_result_is_used(self):
        self.assertIn('ok, reason = self._enqueue(path.name, info, order_id)', self.src)
        self.assertIn('info["queue_error"] = reason', self.src)
        self.assertIn('"Файл не попал в очередь"', self.src)

    def test_silent_swallow_is_gone(self):
        block = self.src.split('if action == "queue":', 1)[1].split("# оригинал", 1)[0]
        self.assertNotIn("except Exception:\n                pass", block,
                         "ошибка постановки в очередь снова глотается")


# ================================================================
# 18.8 (срез 7): папка как главный путь — FarmLoop-флаг, склад и API
# ================================================================

FARMLOOP_GCODE = (
    "; generated by PrintFlow slicer\n"
    "; filament PLA\n"
    "; PRINTFLOW FARMLOOP BEGIN\n"
    "G91\n"
    "G1 Z5 F3000\n"
    "; PRINTFLOW FARMLOOP END\n"
    "G28\n"
    "G1 X10 Y10\n"
)


class FarmloopMarkerTests(unittest.TestCase):
    """G-code из папки: маркер FarmLoop-блока пробрасывается в pending."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        root = pathlib.Path(self.tmp.name)
        self.uploads = root / "uploads"
        self.db = Database(root / "watch.sqlite3")
        self.addCleanup(self.db.close)
        self.manager = FakeManager()
        self.wf = WatchFolder(self.db, manager=self.manager, bus=None)

    def _handle(self, text: str) -> dict:
        src = pathlib.Path(self.tmp.name) / "detal.gcode"
        src.write_text(text, encoding="utf-8")
        with mock.patch.object(watch_folder_mod, "UPLOAD_DIR", self.uploads):
            self.wf._handle_file(src)
        self.assertEqual(1, len(self.wf._pending))
        item = next(iter(self.wf._pending.values()))
        self.assertFalse(item.get("error"), f"ошибка разбора: {item.get('error')}")
        self.assertTrue((self.uploads / "detal.gcode").exists(),
                        "копия в uploads — иначе очередь не напечатает файл")
        return item

    def test_farmloop_marker_is_flagged(self):
        self.assertTrue(self._handle(FARMLOOP_GCODE)["farmloop"])

    def test_plain_gcode_is_not_flagged(self):
        text = FARMLOOP_GCODE.replace("; PRINTFLOW FARMLOOP BEGIN\n", "")
        self.assertFalse(self._handle(text)["farmloop"])

    def test_list_pending_returns_fid(self):
        """18.8: fid в каждом элементе — UI адресует кликнутый файл,
        а не первый pending (баг 17.x: fid не отдавался)."""
        self._handle(FARMLOOP_GCODE)
        items = self.wf.list_pending()
        self.assertEqual(1, len(items))
        fid = items[0]["fid"]
        self.assertNotEqual("", fid)
        self.assertIn(fid, self.wf._pending)
        self.assertEqual(items[0]["name"], self.wf.get_pending(fid)["name"])


class WarehouseSpoolTests(unittest.TestCase):
    """pick_warehouse_spool: склад сам знает, какой бобиной печатать."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.db = Database(pathlib.Path(self.tmp.name) / "spools.sqlite3")
        self.addCleanup(self.db.close)

    def _spool(self, sid: str, **kw) -> None:
        row = {"id": sid, "material": "PLA", "remaining_grams": 1000.0,
               "total_grams": 1000.0, "ams_slot": "", "verified": 1, "archived": 0}
        row.update(kw)
        self.db.upsert("spools", row, key="id")

    def test_no_match_returns_none(self):
        self._spool("sp_1")
        self.assertIsNone(pick_warehouse_spool(self.db, "PETG"))
        self.assertIsNone(pick_warehouse_spool(self.db, ""))

    def test_match_is_case_insensitive(self):
        self._spool("sp_1", material="pla")
        self.assertEqual("sp_1", pick_warehouse_spool(self.db, "PLA")["id"])

    def test_ams_spool_wins(self):
        self._spool("sp_plain")
        self._spool("sp_ams", ams_slot="3")
        self.assertEqual("sp_ams", pick_warehouse_spool(self.db, "PLA")["id"])

    def test_empty_and_archived_are_skipped(self):
        self._spool("sp_empty", remaining_grams=0)
        self._spool("sp_arch", archived=1)
        self._spool("sp_ok", remaining_grams=120.0)
        self.assertEqual("sp_ok", pick_warehouse_spool(self.db, "PLA")["id"])


class WatchConveyorApiTests(unittest.TestCase):
    """/api/watch/ensure + /api/watch/enqueue: серия конвейера и катушка
    со склада — реальный PrinterManager на временной базе."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.db = make_db()
        self.addCleanup(self.db.close)
        self.manager = PrinterManager(self.db, Repo(self.db))
        if getattr(self.manager, "watch", None) is not None:
            self.manager.watch.stop()
        # тесты не должны дергать реальный LAN: студийный шлюз глушим
        self.manager.studio = None
        self.db.upsert("settings", {"key": "auto_queue", "value": "0"}, key="key")
        self.api = Api.__new__(Api)
        self.api.db = self.db
        self.api.manager = self.manager
        self.wf = self.manager.watch
        self._spool_row = {"id": "sp_w", "material": "PLA", "remaining_grams": 500.0,
                           "total_grams": 1000.0, "ams_slot": "3", "verified": 1,
                           "archived": 0}
        self.db.upsert("spools", self._spool_row, key="id")

    def _pending(self, fid: str, **info) -> str:
        row = {"file": f"/tmp/{fid}.gcode", "name": f"{fid}.gcode",
               "material": "PLA", "order_id": ""}
        row.update(info)
        self.wf._pending[fid] = row
        return fid

    def _jobs(self):
        return self.db.query("SELECT * FROM print_jobs ORDER BY datetime(created_at), id")

    def test_ensure_creates_folder(self):
        target = pathlib.Path(self.tmp.name) / "Inbox"
        self.db.upsert("settings", {"key": "watch_folder_path", "value": str(target)}, key="key")
        code, body = self.api.post("/api/watch/ensure", {}, {})
        self.assertEqual(200, code)
        self.assertTrue(body["ok"])
        self.assertTrue(body["exists"])
        self.assertTrue(target.is_dir())

    def test_ensure_without_path_refused(self):
        # дефолт пути сидится в БД из config: очищаем явно
        self.db.upsert("settings", {"key": "watch_folder_path", "value": ""}, key="key")
        with self.assertRaises(ValueError):
            self.api.post("/api/watch/ensure", {}, {})

    def test_series_enqueue_with_farmloop_flag(self):
        fid = self._pending("wf_s1", farmloop=True)
        code, body = self.api.post(
            "/api/watch/enqueue", {"fid": fid, "cycles": 3, "ams_mapping": []}, {})
        self.assertEqual(200, code)
        self.assertEqual("sp_w", body["spool_id"])
        self.assertEqual(3, body["cycles"])
        self.assertEqual(3, len(body["job"]["series"]["job_ids"]))
        jobs = self._jobs()
        self.assertEqual(3, len(jobs))
        for one in jobs:
            self.assertEqual("sp_w", one["spool_id"])
            self.assertEqual("PLA", one["material"])
            self.assertEqual([3], json.loads(one["ams_mapping"]))
        self.assertFalse(fid in self.wf._pending, "pending снят после постановки")
        events = self.db.query("SELECT * FROM events WHERE kind='farmloop'")
        self.assertTrue(events)

    def test_series_refused_without_farmloop_flag(self):
        fid = self._pending("wf_s2", farmloop=False)
        with self.assertRaises(ValueError) as ctx:
            self.api.post("/api/watch/enqueue", {"fid": fid, "cycles": 3}, {})
        self.assertIn("FarmLoop", str(ctx.exception))
        self.assertFalse(self._jobs())

    def test_plain_enqueue_picks_warehouse_spool(self):
        fid = self._pending("wf_p1")
        code, body = self.api.post(
            "/api/watch/enqueue", {"fid": fid, "ams_mapping": []}, {})
        self.assertEqual(200, code)
        self.assertEqual("sp_w", body["spool_id"])
        self.assertNotIn("series", body["job"])
        job = self._jobs()[0]
        self.assertEqual("sp_w", job["spool_id"])
        self.assertEqual([3], json.loads(job["ams_mapping"]))

    def test_plain_enqueue_without_spool_match(self):
        self.db.query("DELETE FROM spools", ())
        fid = self._pending("wf_p2", material="PETG")
        code, body = self.api.post(
            "/api/watch/enqueue", {"fid": fid, "ams_mapping": [2]}, {})
        self.assertEqual(200, code)
        self.assertEqual("", body["spool_id"])
        job = self._jobs()[0]
        self.assertIsNone(job["spool_id"])
        self.assertEqual([2], json.loads(job["ams_mapping"]))


if __name__ == "__main__":
    unittest.main()
