"""Поведение FarmLoop Stage 1: подготовка G-code без риска повторной обработки."""
from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from connector.printflow.farmloop import (
    BEGIN,
    END,
    FarmLoopError,
    prepare_file,
    prepare_gcode,
    profile_payload,
    validate_template,
)


SOURCE = """; generated by Bambu Studio
M104 S220
M140 S60
G28
G1 Z0.2 F1200
G1 X20 Y20 E1 F1800
M104 S0
M140 S0
"""

TEMPLATE = f"""{BEGIN}
; verified for the installed P1S Stage 1 kit
G1 X200 F6000
G1 Y250 F6000
{END}"""


class FarmLoopRouteTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        import connector.printflow.routes_farmloop  # noqa: F401

    def test_profile_reports_uninstalled_template_without_claiming_ready(self):
        from connector.printflow.router import router
        code, payload = router.dispatch(None, "GET", "/api/farmloop/profile", query={})
        self.assertEqual(code, 200)
        self.assertEqual(payload["id"], "bambu-p1s-farmloop-stage1")
        self.assertFalse(payload["template_installed"])
        self.assertFalse(payload["can_prepare"])
        self.assertIn("шаблон", payload["blocked_reason"])


class FarmLoopTemplateTests(unittest.TestCase):
    def test_valid_template_is_described(self):
        out = validate_template(TEMPLATE)
        self.assertEqual(out["profile"], "bambu-p1s-farmloop-stage1")
        self.assertEqual(out["commands"], 2)

    def test_empty_template_is_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "пустой"):
            validate_template(f"{BEGIN}\n; only comment\n{END}")

    def test_template_without_motion_is_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "движения"):
            validate_template(f"{BEGIN}\nM400\n{END}")

    def test_duplicate_markers_are_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "ровно один"):
            validate_template(TEMPLATE + "\n" + BEGIN + "\n" + END)


class FarmLoopPreparationTests(unittest.TestCase):
    def test_prepare_preserves_source_and_adds_metadata(self):
        output, report = prepare_gcode(
            SOURCE, TEMPLATE,
            metadata={"job_id": "job-7", "cycle": "2", "cycles": "10", "ams": "AMS1/3"},
        )
        self.assertTrue(output.startswith(SOURCE))
        self.assertIn(BEGIN, output)
        self.assertIn("; job_id: job-7", output)
        self.assertIn("; cycle: 2", output)
        self.assertIn("; ams: AMS1/3", output)
        self.assertTrue(report["injected"])
        self.assertEqual(output.count(BEGIN), 1)
        self.assertEqual(output.count(END), 1)

    def test_already_prepared_file_is_rejected(self):
        prepared, _ = prepare_gcode(SOURCE, TEMPLATE)
        with self.assertRaisesRegex(FarmLoopError, "уже содержит"):
            prepare_gcode(prepared, TEMPLATE)

    def test_non_fdm_source_is_rejected(self):
        with self.assertRaisesRegex(FarmLoopError, "сопла"):
            prepare_gcode("; just text\nG1 X1", TEMPLATE)

    def test_height_warning_does_not_silently_change_file(self):
        source = SOURCE + "\nG1 Z220 F600\n"
        output, report = prepare_gcode(source, TEMPLATE)
        self.assertIn("Высота", report["warnings"][0])
        self.assertIn("G1 Z220", output)

    def test_source_and_destination_must_differ(self):
        with tempfile.TemporaryDirectory() as folder:
            path = Path(folder) / "job.gcode"
            path.write_text(SOURCE, encoding="utf-8")
            with self.assertRaisesRegex(FarmLoopError, "разными"):
                prepare_file(path, path, TEMPLATE)

    def test_profile_is_explicit(self):
        payload = profile_payload()
        self.assertEqual(payload["printer"], "Bambu Lab P1S")
        self.assertEqual(payload["stage"], "Stage 1")
        self.assertTrue(payload["requires_verified_template"])


class FarmLoopConstructorAndCleanTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        import connector.printflow.routes_farmloop  # noqa: F401

    def test_build_and_parse_template_blocks(self):
        from connector.printflow.farmloop import build_template_from_blocks, parse_template_blocks
        gcode = build_template_from_blocks(
            cooldown_temp=38, fan_assist=True, z_lift=18.0, pusher_y=242.0,
            pusher_speed=2500, custom_gcode="M300 S440 P100\n",
        )
        self.assertIn("M190 R38", gcode)
        self.assertIn("G1 Z18.0 F1200", gcode)
        self.assertIn("G1 Y242.0 F2500", gcode)
        self.assertIn("M300 S440 P100", gcode)
        blocks = parse_template_blocks(gcode)
        self.assertEqual(blocks["cooldown_temp"], 38)
        self.assertTrue(blocks["fan_assist"])
        self.assertEqual(blocks["z_lift"], 18.0)
        self.assertEqual(blocks["pusher_y"], 242.0)
        self.assertEqual(blocks["pusher_speed"], 2500)
        self.assertIn("M300", blocks["custom_gcode"])

    def test_template_get_and_post_lifecycle(self):
        import types
        from unittest import mock
        from connector.printflow.router import router
        with tempfile.TemporaryDirectory() as tmp:
            tmp_data = Path(tmp)
            with mock.patch("connector.printflow.routes_farmloop.DATA_DIR", tmp_data):
                # 1. Сначала шаблон не установлен
                code, res = router.dispatch(None, "GET", "/api/farmloop/template", query={})
                self.assertEqual(code, 200)
                self.assertFalse(res["template_installed"])
                self.assertTrue(res["gcode"])
                self.assertEqual(res["blocks"]["cooldown_temp"], 35)

                # 2. Сохраняем шаблон блоками конструктора
                api = types.SimpleNamespace(db=None)
                code, res = router.dispatch(api, "POST", "/api/farmloop/template", body={
                    "blocks": {
                        "cooldown_temp": 40,
                        "fan_assist": True,
                        "z_lift": 20.0,
                        "pusher_y": 240.0,
                        "pusher_speed": 2200,
                        "custom_gcode": "; comment\n",
                    }
                })
                self.assertEqual(code, 200)
                self.assertTrue(res["template_installed"])
                self.assertEqual(res["blocks"]["cooldown_temp"], 40)

                # 3. Теперь GET сообщает, что шаблон установлен
                code, res = router.dispatch(None, "GET", "/api/farmloop/template", query={})
                self.assertEqual(code, 200)
                self.assertTrue(res["template_installed"])
                self.assertEqual(res["blocks"]["cooldown_temp"], 40)

    def test_test_clean_safety_checks(self):
        import types
        from unittest import mock
        from connector.printflow.router import router
        with tempfile.TemporaryDirectory() as tmp:
            tmp_data = Path(tmp)
            with mock.patch("connector.printflow.routes_farmloop.DATA_DIR", tmp_data):
                sent_commands = []
                printer = types.SimpleNamespace(
                    id="p1",
                    record={"name": "Тестовый P1S"},
                    connected=True,
                    snapshot=lambda: {"printer": {"state": "IDLE", "bed_temp": 32}},
                    gcode=lambda cmd: sent_commands.append(cmd),
                )
                manager = types.SimpleNamespace(get=lambda pid: printer)
                api = types.SimpleNamespace(db=None, manager=manager)

                # 1. Отказ без подтверждения confirmed: true
                code, res = router.dispatch(api, "POST", "/api/farmloop/test-clean", body={})
                self.assertEqual(code, 400)
                self.assertIn("Подтвердите", res["error"])

                # 2. Отказ, если шаблон ещё не установлен
                code, res = router.dispatch(api, "POST", "/api/farmloop/test-clean", body={"confirmed": True})
                self.assertEqual(code, 400)
                self.assertIn("не установлен", res["error"])

                # Устанавливаем шаблон
                tmpl_dir = tmp_data / "farmloop-templates"
                tmpl_dir.mkdir(parents=True)
                (tmpl_dir / "bambu-p1s-farmloop-stage1.gcode").write_text(
                    f"{BEGIN}\nG1 Z10 F1200\nG1 Y200 F2400\n{END}\n", encoding="utf-8")

                # 3. Отказ, если принтер занят (RUNNING)
                printer.snapshot = lambda: {"printer": {"state": "RUNNING", "bed_temp": 60}}
                code, res = router.dispatch(api, "POST", "/api/farmloop/test-clean", body={"confirmed": True})
                self.assertEqual(code, 400)
                self.assertIn("Принтер занят", res["error"])

                # 4. Успешный запуск, когда принтер IDLE
                printer.snapshot = lambda: {"printer": {"state": "IDLE", "bed_temp": 30}}
                code, res = router.dispatch(api, "POST", "/api/farmloop/test-clean", body={"confirmed": True})
                self.assertEqual(code, 200)
                self.assertTrue(res["ok"])
                self.assertEqual(res["executed_commands"], 2)
                self.assertEqual(sent_commands, ["G1 Z10 F1200", "G1 Y200 F2400"])


if __name__ == "__main__":
    unittest.main()
